2q-qvm --> 4q-pyqvm
ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it
qc = get_qc('2q-qvm') --> qc = get_qc('4q-pyqvm')